import fs from "node:fs";
const boundary=JSON.parse(fs.readFileSync("research/woit-lisi-isomorph/woit/W_REGROUNDED_PRIMITIVE_DOMAIN_BOUNDARY_0_1.json","utf8"));
const ledger=JSON.parse(fs.readFileSync("research/woit-lisi-isomorph/woit/CORE021_CLOSURE_LEDGER_0_59.json","utf8"));
const errors=[];
const open=ledger.dispositions.filter(d=>d.closure_mode==="INCOMPLETE_UNEXPANDED").map(d=>d.census_id).sort();
const assigned=Object.values(boundary.categories).flatMap(c=>c.ids).sort();
const dup=[...new Set(assigned.filter((x,i,a)=>a.indexOf(x)!==i))];
if(boundary.status!=="GENUINE_PRIMITIVE_DOMAIN_BOUNDARY_W_TRACK")errors.push("boundary status");
if(open.length!==84)errors.push("ledger open count");
if(assigned.length!==84||new Set(assigned).size!==84)errors.push("boundary assignment cardinality");
if(dup.length)errors.push("duplicate boundary assignment");
if(JSON.stringify(open)!==JSON.stringify(assigned))errors.push("boundary/open-set mismatch");
if(boundary.current_authority?.closed_primitive!==67||boundary.current_authority?.incomplete_unexpanded!==84)errors.push("authority counts");
if(boundary.current_authority?.ia_fixed_point!==null||boundary.current_authority?.nei!==false||boundary.current_authority?.dts!==false||boundary.current_authority?.dp!==false)errors.push("downstream gate state");
if(!boundary.qualification_evidence?.finding?.includes("No qualified generic algebra"))errors.push("qualification finding missing");
if((boundary.prohibited_actions||[]).length<4)errors.push("anti-drift guards missing");
if((boundary.lawful_unblock_paths||[]).length<2)errors.push("unblock paths missing");
const result={pass:errors.length===0,errors,open_count:open.length,category_counts:Object.fromEntries(Object.entries(boundary.categories).map(([k,v])=>[k,v.ids.length]))};
console.log(JSON.stringify(result,null,2));
if(!result.pass)process.exitCode=1;