import fs from "node:fs";
const root="research/primitive-demand-qualification";
const source=JSON.parse(fs.readFileSync(root+"/SOURCE_DEMAND_CENSUS_0_1.json","utf8"));
const profile=JSON.parse(fs.readFileSync(root+"/SEMANTIC_OCCURRENCE_EXTRACTION_PROFILE_0_1.json","utf8"));
const heads=[...profile.surface_relation_heads].sort((a,b)=>b.length-a.length||a.localeCompare(b));
function clauses(text){const out=[];let start=0,ci=1;const push=(s,e)=>{const raw=text.slice(s,e),lead=raw.search(/\S/);if(lead<0)return;const a=s+lead,tr=text.slice(a,e).replace(/\s+$/,""),b=a+tr.length;out.push({index:ci++,start:a,end:b,text:text.slice(a,b)});};for(let i=0;i<text.length;i++)if(text[i]==="."||text[i]===";"){push(start,i);start=i+1;}push(start,text.length);return out;}
function findHeads(text){const low=text.toLowerCase(),out=[],used=[];for(const h of heads){let pos=0;while((pos=low.indexOf(h,pos))>=0){const end=pos+h.length,pre=pos?low[pos-1]:" ",post=end<low.length?low[end]:" ";const ok=!/[a-z0-9_]/.test(pre)&&!/[a-z0-9_]/.test(post)&&!used.some(([a,b])=>pos<b&&end>a);if(ok){out.push({normalized_head:h,start:pos,end,text:text.slice(pos,end)});used.push([pos,end]);}pos=Math.max(pos+1,end);}}return out.sort((a,b)=>a.start-b.start||a.end-b.end);}
let clauseCount=0,headCount=0,zeroHead=0,oneHead=0,multiHead=0;
const items=source.items.map(it=>{const cs=clauses(it.body).map(c=>{const hs=findHeads(c.text).map((h,hi)=>({occurrence_id:\`G1-\${it.census_id}-C\${String(c.index).padStart(3,"0")}-H\${String(hi+1).padStart(3,"0")}\`,kind:"SURFACE_RELATION_HEAD_LOCATOR",body_start:c.start+h.start,body_end:c.start+h.end,exact_text:h.text,normalized_head:h.normalized_head,semantic_state:"UNEXPANDED_SEMANTIC_OCCURRENCE",argument_roles:"UNRESOLVED",semantic_arity:"UNRESOLVED",load_bearing_status:"REQUIRES_SOURCE_LOCAL_G1_REVIEW"}));clauseCount++;headCount+=hs.length;if(!hs.length)zeroHead++;else if(hs.length===1)oneHead++;else multiHead++;return {clause_id:\`\${it.census_id}-C\${String(c.index).padStart(3,"0")}\`,body_start:c.start,body_end:c.end,exact_text:c.text,surface_relation_heads:hs,extraction_state:hs.length?"SURFACE_HEADS_LOCATED_G1_REVIEW_REQUIRED":"OCCURRENCE_EXTRACTION_INCOMPLETE",semantic_review_required:true,note:"Surface-head location does not establish complete semantic occurrence extraction."};});return {track:it.track,census_id:it.census_id,source_provenance:it.source_provenance,source_state:it.state,exact_body:it.body,body_length:it.body.length,clauses:cs,g1_state:"G1_REVIEW_REQUIRED"};});
const out={schema:"isograph.semantic-occurrence-census.working.v0.1",date:"2026-10-06",status:"G1_WORKING_SURFACE_LOCATOR_PASS_NOT_SEMANTICALLY_COMPLETE",method:"PRIMITIVE_DEMAND_GRAPH_FIRST_METHOD_0_2.md",profile:"SEMANTIC_OCCURRENCE_EXTRACTION_PROFILE_0_1.json",frozen_input:{path:"SOURCE_DEMAND_CENSUS_0_1.json",blob:profile.input.blob},authority:{semantic_authority:false,g1_complete:false,g2_neutral_graph_complete:false,g3_core_definability_authorized:false,g4_structural_quotient_authorized:false,W_or_L_consumption_authorized:false},counts:{bodies:items.length,W:items.filter(x=>x.track==="W").length,L:items.filter(x=>x.track==="L").length,clauses:clauseCount,surface_relation_head_occurrences:headCount,clauses_with_zero_surface_heads:zeroHead,clauses_with_one_surface_head:oneHead,clauses_with_multiple_surface_heads:multiHead,clauses_requiring_semantic_review:clauseCount},guards:["No mathematical category is inferred from a source-domain noun.","No surface relation head is treated as a primitive or schema.","No candidate-basis edge is admitted.","No W/L cross-track semantic premise is admitted.","Every clause remains review-required; this artifact cannot be cited as G1 completion."],items};
fs.writeFileSync(root+"/SEMANTIC_OCCURRENCE_CENSUS_WORKING_0_1.json",JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify(out.counts,null,2));